### PR TITLE
Trees, template recursion an multiple vocabs

### PR DESCRIPTION
**Pull request by ryansroberts**

### CODE REVIEW

**Comment by ryansroberts** [comment]
We gonna merge this? @NSmeef  @jameskirk84

**Comment by ryansroberts** [comment]
I prefer 'first committer wins' merge conflict allocation :)

**Comment by jameskirk84** [comment]
we are currently manually merging this as we speak! and may need to talk to you about it... ;-)

**Comment by jameskirk84** [comment]
Lovely friday afternoon merge session.  Trying to merge this and master which includes filter persistence

**Comment by ryansroberts** [comment]
Dev branch?

**Comment by jameskirk84** [comment]
Its on the nested_vocab_merge branch and it builds and we've got a red test to fix. Didnt get round to fixing it today though. Monday

**Pull request merged**
